---
title: 'Group 6 Final Project: Codes and Technical Analysis'
author: "Junran Cao, Jordan Dawes, and Carter Rogers"
date: "`r Sys.Date()`"
output: html_document:
    code_folding: hide
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
library(dplyr)
library(ggplot2)
library(tidyr)
library(gridExtra)
library(tidyverse)  
library(corrplot)
library(ezids)
library(httr)
library(randomForest)
library(tree)
library(caret)
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3, scipen = 999) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

# Loading and cleaning data

```{r}
dataset <- read.csv("~/Downloads/US_Accidents_Dec20_updated.csv")
dataset <- na.omit(dataset) #335,552 observations remaining
```

```{r}
#encoding correct datatypes
dataset$ID <- as.character(dataset$ID)
dataset$Severity <- as.factor(dataset$Severity)
dataset$Start_Time <- as.character(dataset$Start_Time)
dataset$End_Time <- as.character(dataset$End_Time)
dataset$Description <- as.character(dataset$Description)
dataset$Street <- as.character(dataset$Street)
dataset$City <- as.character(dataset$City)
dataset$County <- as.character(dataset$County)
dataset$State <- as.character(dataset$State)
dataset$Zipcode <- as.numeric(dataset$Zipcode)
dataset$Airport_Code <- as.character(dataset$Airport_Code)
dataset$Weather_Timestamp <- as.character(dataset$Weather_Timestamp)
dataset$Weather_Condition <- as.character(dataset$Weather_Condition)
```

```{r}
#remove unnecessary columns
dataset <- subset(dataset, select = -c(Number, Street, Side, Airport_Code, Weather_Timestamp, Start_Lat, Start_Lng, End_Lat, End_Lng))
```

# EDA

```{r}
table(dataset$Severity) #vast majority are severity 2, why?
table(dataset$State) #states w/large pop have most accidents, no surprises there
ggplot(data = dataset, aes(x = Severity, y = Distance.mi.)) + geom_boxplot() #looks wacky with most distances = 0
ggplot(data = dataset, aes(x = Distance.mi.)) + geom_histogram(binwidth = .05) + scale_x_continuous(limits = c(0, 10)) #may need to omit distances of 0
ggplot(data = dataset, aes(x = Temperature.F., y = Wind_Speed.mph., colour = Severity)) + geom_point() + scale_y_continuous(limits = c(0, 50))
```


```{r}

loadPkg("dplyr")

#Renaming relevant columns 
dataset <- rename(dataset, c("civ.light" = "Civil_Twilight"),c("vis" = "Visibility.mi."))
#visibility in miles
dataset$civ.light <- as.factor(dataset$civ.light)
str(dataset)

#nas <- subset(dataset, is.na(dataset$civ.light))
#nas

dataset2 <- subset(dataset, civ.light != "")
visdata <- subset(dataset2, vis < 11)
#visdata

qqnorm(visdata$vis)
qqline(visdata$vis)

loadPkg("ggplot2")
ggplot(visdata, aes(x=civ.light)) +
  geom_bar(col="yellow",fill="purple") + labs(title = "Bar Plot")

#ggplot(dataset, aes(x=vis)) +
#  geom_bar(col="yellow",fill="purple") + labs(title = "Visibility Bar Plot")

ggplot(visdata, aes(x=vis, y=civ.light)) +
  geom_point(size=2, shape=23)


ggplot(visdata, aes(y=vis, x=civ.light, fill= civ.light)) +
  geom_bar(stat='identity') +
  labs(title="Total Accidents based on Daylight",
       x="Daylight Status",
       y="Number of Accidents",
       fill="Daylight Status")

ggplot(data = visdata, aes(vis)) + geom_histogram(mapping = aes(x = vis), binwidth = 1)

#ggplot(data = visdata, aes(civ.light)) + geom_bar()
ggplot(data = visdata, mapping = aes(x = vis, colour = Severity)) +
  geom_freqpoly(binwidth = 0.1)

ggplot(data = visdata, mapping = aes(x = Severity, y = vis)) + 
  geom_boxplot(mapping = aes(Severity))

#plot_num(visdata)

#use one way anova to test severity and visibility
#chi squared test for severity and civ.light
#tree model, KNN 
```

# Can we classify the severity of a given accident based on temperature, wind speed, or other weather conditions present during the accident?

```{r}
#try decision trees and random forests instead

set.seed(123)

newdata2 <- subset(dataset, select = c(Severity, Temperature.F., Wind_Speed.mph., Wind_Chill.F., Humidity..., Pressure.in., vis, Precipitation.in.))

#scale vars
scaleddata2 <- as.data.frame(scale(newdata2[2:8], center = TRUE, scale = TRUE))
scaleddata2 <- cbind(newdata2[,1], scaleddata2)
names(scaleddata2)[1] <- 'Severity'

trainIndex2 <- createDataPartition(scaleddata2$Severity, p = .7, list = FALSE, times = 1)
carter_train2 <- scaleddata2[trainIndex2,]
carter_test2 <- scaleddata2[-trainIndex2,]

rf_model2 <- randomForest(Severity ~ .
                    , data = carter_train2
                    , mtry = 3
                    , ntree = 20
                    , importance = TRUE
                    , type = "prob")

predicted_table <- predict(rf_model2, carter_test2[,-1])
table(observed = carter_test2[,1], predicted = predicted_table)
print(rf_model2)
round(importance(rf_model2), 2)

#stratified sampling
rf_model3 <- randomForest(Severity ~ .
                    , data = carter_train2
                    , mtry = 3
                    , ntree = 20
                    , importance = TRUE
                    , type = "prob"
                    , sampsize = c(1000, 1000, 1000, 1000))

predicted_table2 <- predict(rf_model3, carter_test2[,-1])
table(observed = carter_test2[,1], predicted = predicted_table2)
print(rf_model3)
round(importance(rf_model3), 2)
```

#What factors best predict the severity of an accident?

```{r}
#remove all cols except numeric, factor, and binary. Also excluding Distance since this is not a "predictive" metric but rather a rough measurement of severity
rf_data = subset(dataset, select = -c(ID, Start_Time, End_Time, Distance.mi., Description, City, County, State, Zipcode, Country, Weather_Condition))

#split train-test
rf_trainIndex <- createDataPartition(rf_data$Severity, p = .7, list = FALSE, times = 1)
rf_carter_train <- rf_data[rf_trainIndex,]
rf_carter_test <- rf_data[-rf_trainIndex,]

rf_model <- randomForest(Severity ~ .
                    , data = rf_carter_train
                    , mtry = 5
                    , ntree = 20
                    , importance = TRUE
                    , type = "prob")

varImpPlot(rf_model, n.var = 5, main = "Variable Importance Plot for Random Forest Model (Severity)")
#wind direction, humidity, temperature appear in both plots
```